package com.meituan.qa.meishi.Hui.dto;

// Generated by https://quicktype.io



import java.util.List;

public class PromoResponse {
    private Shoppromo shoppromo;
    private ShopcouponClass coupon;
    private ShopcouponClass shopcoupon;
    private List<Gift> gifts;
    private long platform;

    public Shoppromo getShoppromo() {
        return shoppromo;
    }

    public void setShoppromo(Shoppromo value) {
        this.shoppromo = value;
    }

    public ShopcouponClass getCoupon() {
        return coupon;
    }

    public void setCoupon(ShopcouponClass value) {
        this.coupon = value;
    }

    public ShopcouponClass getShopcoupon() {
        return shopcoupon;
    }

    public void setShopcoupon(ShopcouponClass value) {
        this.shopcoupon = value;
    }

    public long getPlatform() {
        return platform;
    }

    public void setPlatform(long value) {
        this.platform = value;
    }

    public List<Gift> getGifts() {
        return gifts;
    }

    public void setGifts(List<Gift> gifts) {
        this.gifts = gifts;
    }
}

